twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        database_url: "%env(resolve:DATABASE_URL)%"
    form_themes:
        - bootstrap_4_layout.html.twig

